#!/usr/bin/env bash

IFS=$'\n'
for show in $(cat "$1"); do
	cities=$(echo "$show" | cut -d'|' -f 2) # | cut -d"," -f 1)
	for city in "$cities"; do
		city_venues=$(grep "$city" "$1" | cut -d'|' -f 3 | awk '!a[$0]++' | perl -pe 's/\n/, /g;' | perl -pe 's/, $//g') 
		if [ -z "$list" ]; then
			list=$(echo "$(echo $city | cut -d',' -f1): $city_venues") 
		else
			list=$(echo -e "$list\n$(echo $city | cut -d',' -f1): $city_venues") 
		fi
			
	done
done
echo "$list" | awk '!a[$0]++'
